USE thaipara;

ALTER TABLE ATHLETE ADD FOREIGN KEY (uid) REFERENCES USERS(id);

ALTER TABLE EVENTS ADD FOREIGN KEY (sport_id) REFERENCES SPORT(id);

ALTER TABLE COMPETES_IN ADD FOREIGN KEY (athlete_id) REFERENCES ATHLETE(id);
ALTER TABLE COMPETES_IN ADD FOREIGN KEY (event_id) REFERENCES EVENTS(id);

ALTER TABLE MEMBER_OF ADD FOREIGN KEY (team_id) REFERENCES TEAMS(id);
ALTER TABLE MEMBER_OF ADD FOREIGN KEY (athlete_id) REFERENCES ATHLETE(id);

ALTER TABLE PARTICIPATES_IN ADD FOREIGN KEY (team_id) REFERENCES TEAMS(id);
ALTER TABLE PARTICIPATES_IN ADD FOREIGN KEY (event_id) REFERENCES EVENTS(id);
